name: AquaPilates
favicon: null
layout_spectrum: 0.15196495619602501
typography_spectrum: 0.00728587293997407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000203'
    - '#fbfff7'
    - '#00304e'
    - '#08699e'
    - '#a7b1b2'
  brandStrength: 0.2721383005846292
  lightness: 0.4201573522295803
  saturation: 0.39301765337586403
  rhythmicContrast: 0.002437769202515483
purpose: []
