name: AquaPilates
favicon: null
layout_spectrum: 0.15196495619602501
typography_spectrum: 0.00728587293997407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d80a9'
    - '#7de351'
    - '#64c598'
    - '#a7dfc4'
  brandStrength: 0.2721383005846292
  lightness: 0.4201573522295803
  saturation: 0.39301765337586403
  rhythmicContrast: 0.002437769202515483
purpose: []
